# Generated by Django 6.0.3 on 2026-09-24 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255, verbose_name='Nombre del evento')),
                ('lugar', models.CharField(max_length=255, verbose_name='Lugar')),
                ('fecha_inicio', models.DateField(verbose_name='Fecha de inicio')),
                ('fecha_final', models.DateField(verbose_name='Fecha final')),
                ('hora', models.TimeField(verbose_name='Hora del evento')),
                ('duracion_horas', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Duración del evento (horas)')),
                ('limite_diario_horas', models.DecimalField(decimal_places=2, max_digits=4, verbose_name='Límite diario de trabajo (horas)')),
                ('notas_produccion', models.TextField(blank=True, null=True, verbose_name='Notas de producción')),
            ],
        ),
    ]
