# Generated by Django 6.0.3 on 2026-09-24 23:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subtarea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gestion', models.CharField(max_length=255, verbose_name='Nueva gestión')),
                ('categoria', models.CharField(choices=[('SALON', 'Salón'), ('INVITACIONES', 'Invitaciones'), ('CATERING', 'Catering'), ('PROVEEDORES', 'Proveedores'), ('OTRO', 'Otro')], max_length=50, verbose_name='Categoría')),
                ('estimacion_horas', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Estimación (horas)')),
                ('plazo', models.DateField(verbose_name='Plazo (fecha)')),
                ('hora_limite', models.TimeField(verbose_name='Hora límite')),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subtareas', to='api.evento')),
            ],
        ),
    ]
