# Generated by Django 6.0.3 on 2026-09-25 00:00

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_subtarea'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='creado_en',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Creado en'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='evento',
            name='tipo',
            field=models.CharField(default='Lanzamiento', max_length=50, verbose_name='Tipo de evento'),
        ),
        migrations.AddField(
            model_name='subtarea',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('en_progreso', 'En progreso'), ('hecho', 'Hecho')], default='pendiente', max_length=20, verbose_name='Estado'),
        ),
        migrations.AddField(
            model_name='subtarea',
            name='hora_inicio',
            field=models.TimeField(blank=True, null=True, verbose_name='Hora inicio programado'),
        ),
        migrations.AddField(
            model_name='subtarea',
            name='prioridad',
            field=models.CharField(choices=[('alta', 'Alta'), ('media', 'Media'), ('baja', 'Baja')], default='media', max_length=10, verbose_name='Prioridad'),
        ),
    ]
